import type { Job } from "@/types/job"

export async function getJobs(): Promise<Job[]> {

  return Promise.resolve(mockJobs)
}

export async function getJobById(id: number): Promise<Job | undefined> {

  return Promise.resolve(mockJobs.find((job) => job.id === id))
}

const mockJobs: Job[] = [
  {
    id: 1,
    title: "Frontend Developer",
    company: "TechCorp",
    location: "Bangalore, India",
    salary: "₹12,00,000 - ₹18,00,000",
    postedAt: "2 days ago",
    tags: ["Remote", "Full-Time", "JavaScript", "React"],
    employmentType: "Full-Time",
    description:
      "We are looking for a skilled Frontend Developer to join our team. You will be responsible for building user interfaces and implementing web designs.",
    requirements: [
      "3+ years of experience with JavaScript and React",
      "Strong understanding of HTML, CSS, and responsive design",
      "Experience with modern frontend build tools",
      "Bachelor's degree in Computer Science or related field",
    ],
    responsibilities: [
      "Develop and maintain user interfaces for web applications",
      "Collaborate with designers to implement visual elements",
      "Ensure cross-browser compatibility and responsive design",
      "Optimize applications for maximum speed and scalability",
    ],
  },
  {
    id: 2,
    title: "UX/UI Designer",
    company: "DesignHub",
    location: "Mumbai, India",
    salary: "₹10,00,000 - ₹15,00,000",
    postedAt: "1 week ago",
    tags: ["On-site", "Full-Time", "Figma", "UI/UX"],
    employmentType: "Full-Time",
    description:
      "We're seeking a talented UX/UI Designer to create amazing user experiences. You'll work on designing interfaces for web and mobile applications.",
    requirements: [
      "2+ years of experience in UX/UI design",
      "Proficiency with design tools like Figma and Adobe XD",
      "Understanding of user-centered design principles",
      "Portfolio demonstrating your design skills",
    ],
    responsibilities: [
      "Create wireframes, prototypes, and high-fidelity mockups",
      "Conduct user research and usability testing",
      "Collaborate with developers to implement designs",
      "Maintain design systems and style guides",
    ],
  },
  {
    id: 3,
    title: "Frontend Intern",
    company: "StartupX",
    location: "Hyderabad, India",
    salary: "₹25,000 - ₹35,000 per month",
    postedAt: "3 days ago",
    tags: ["Remote", "Internship", "React", "Entry-Level"],
    employmentType: "Internship",
    description:
      "Join our team as a Frontend Intern and gain valuable experience working on real-world projects. This is a great opportunity for students or recent graduates.",
    requirements: [
      "Basic knowledge of HTML, CSS, and JavaScript",
      "Familiarity with React or similar frameworks",
      "Currently pursuing a degree in Computer Science or related field",
      "Strong problem-solving skills and eagerness to learn",
    ],
    responsibilities: [
      "Assist in developing user interfaces for web applications",
      "Learn and apply best practices in frontend development",
      "Participate in code reviews and team meetings",
      "Work on assigned tasks under the guidance of senior developers",
    ],
  },
  {
    id: 4,
    title: "Full Stack Developer",
    company: "GlobalTech",
    location: "Pune, India",
    salary: "₹15,00,000 - ₹22,00,000",
    postedAt: "5 days ago",
    tags: ["Hybrid", "Full-Time", "JavaScript", "Node.js", "React"],
    employmentType: "Full-Time",
    description:
      "We are looking for a Full Stack Developer to join our growing team. You will work on both frontend and backend development for our web applications.",
    requirements: [
      "4+ years of experience in full stack development",
      "Proficiency with JavaScript, React, and Node.js",
      "Experience with databases (SQL and NoSQL)",
      "Knowledge of cloud services (AWS, Azure, or GCP)",
    ],
    responsibilities: [
      "Develop and maintain web applications from frontend to backend",
      "Design and implement database schemas",
      "Ensure application performance, security, and scalability",
      "Collaborate with cross-functional teams to define and implement new features",
    ],
  },
  {
    id: 5,
    title: "Frontend Engineer",
    company: "InnovateCo",
    location: "Chennai, India",
    salary: "₹14,00,000 - ₹20,00,000",
    postedAt: "1 day ago",
    tags: ["On-site", "Full-Time", "TypeScript", "React", "Next.js"],
    employmentType: "Full-Time",
    description:
      "Join our team as a Frontend Engineer and help build cutting-edge web applications. You'll work with the latest technologies to create exceptional user experiences.",
    requirements: [
      "3+ years of experience with React and TypeScript",
      "Experience with Next.js or similar frameworks",
      "Strong understanding of web performance optimization",
      "Knowledge of testing frameworks like Jest and React Testing Library",
    ],
    responsibilities: [
      "Develop and maintain frontend applications using React and Next.js",
      "Implement responsive designs and ensure cross-browser compatibility",
      "Write clean, maintainable, and well-tested code",
      "Collaborate with backend developers to integrate APIs",
    ],
  },
  {
    id: 6,
    title: "Junior Frontend Developer",
    company: "CodeCraft",
    location: "Gurgaon, India",
    salary: "₹6,00,000 - ₹9,00,000",
    postedAt: "4 days ago",
    tags: ["On-site", "Full-Time", "JavaScript", "React", "Entry-Level"],
    employmentType: "Full-Time",
    description:
      "We're looking for a Junior Frontend Developer to join our team. This is a great opportunity for someone early in their career to grow and learn from experienced developers.",
    requirements: [
      "1+ years of experience with JavaScript and React",
      "Understanding of HTML, CSS, and responsive design",
      "Eagerness to learn and grow as a developer",
      "Bachelor's degree in Computer Science or related field (or equivalent experience)",
    ],
    responsibilities: [
      "Develop user interfaces for web applications under guidance",
      "Implement designs provided by the design team",
      "Write clean and maintainable code",
      "Participate in code reviews and team meetings",
    ],
  },
  {
    id: 7,
    title: "Backend Developer",
    company: "TechSolutions",
    location: "Bangalore, India",
    salary: "₹14,00,000 - ₹20,00,000",
    postedAt: "3 days ago",
    tags: ["On-site", "Full-Time", "Node.js", "Express", "MongoDB"],
    employmentType: "Full-Time",
    description:
      "We are seeking a skilled Backend Developer to join our engineering team. You will be responsible for server-side logic and integration of frontend elements.",
    requirements: [
      "3+ years of experience with Node.js and Express",
      "Strong knowledge of MongoDB or similar NoSQL databases",
      "Experience with RESTful API design",
      "Understanding of server security and performance optimization",
    ],
    responsibilities: [
      "Design and implement scalable backend services",
      "Create and maintain database schemas",
      "Develop and document APIs for frontend consumption",
      "Collaborate with frontend developers to integrate user-facing elements",
    ],
  },
  {
    id: 8,
    title: "DevOps Engineer",
    company: "CloudTech",
    location: "Mumbai, India",
    salary: "₹16,00,000 - ₹25,00,000",
    postedAt: "1 week ago",
    tags: ["Remote", "Full-Time", "AWS", "Docker", "Kubernetes"],
    employmentType: "Full-Time",
    description:
      "Join our team as a DevOps Engineer to build and maintain our cloud infrastructure. You will be responsible for deployment pipelines and system reliability.",
    requirements: [
      "4+ years of experience in DevOps or similar role",
      "Strong knowledge of AWS or other cloud platforms",
      "Experience with containerization using Docker and Kubernetes",
      "Familiarity with CI/CD pipelines and infrastructure as code",
    ],
    responsibilities: [
      "Design and implement cloud infrastructure",
      "Automate deployment processes and monitoring",
      "Ensure system reliability and performance",
      "Collaborate with development teams to streamline operations",
    ],
  },
  {
    id: 9,
    title: "Mobile App Developer",
    company: "AppWorks",
    location: "Hyderabad, India",
    salary: "₹12,00,000 - ₹18,00,000",
    postedAt: "5 days ago",
    tags: ["Hybrid", "Full-Time", "React Native", "Flutter", "Mobile"],
    employmentType: "Full-Time",
    description:
      "We're looking for a talented Mobile App Developer to create innovative applications for iOS and Android platforms using cross-platform technologies.",
    requirements: [
      "3+ years of experience with React Native or Flutter",
      "Knowledge of native app development for iOS or Android",
      "Experience with state management and API integration",
      "Understanding of mobile UI/UX principles",
    ],
    responsibilities: [
      "Develop cross-platform mobile applications",
      "Implement responsive UI designs for various screen sizes",
      "Integrate with backend services and APIs",
      "Optimize app performance and user experience",
    ],
  },
  {
    id: 10,
    title: "Data Scientist",
    company: "DataMinds",
    location: "Pune, India",
    salary: "₹18,00,000 - ₹28,00,000",
    postedAt: "2 days ago",
    tags: ["On-site", "Full-Time", "Python", "Machine Learning", "Data Analysis"],
    employmentType: "Full-Time",
    description:
      "Join our data science team to develop machine learning models and extract insights from complex datasets to drive business decisions.",
    requirements: [
      "Master's or PhD in Computer Science, Statistics, or related field",
      "3+ years of experience in data science or machine learning",
      "Proficiency in Python and data analysis libraries",
      "Experience with machine learning frameworks like TensorFlow or PyTorch",
    ],
    responsibilities: [
      "Develop and implement machine learning models",
      "Analyze large datasets to extract actionable insights",
      "Collaborate with product teams to integrate ML solutions",
      "Present findings and recommendations to stakeholders",
    ],
  },
  {
    id: 11,
    title: "Product Manager",
    company: "InnovateTech",
    location: "Bangalore, India",
    salary: "₹20,00,000 - ₹30,00,000",
    postedAt: "1 week ago",
    tags: ["On-site", "Full-Time", "Product Management", "Agile"],
    employmentType: "Full-Time",
    description:
      "We are looking for an experienced Product Manager to lead the development of our digital products from conception to launch.",
    requirements: [
      "5+ years of experience in product management",
      "Strong understanding of software development lifecycle",
      "Experience with Agile methodologies",
      "Excellent communication and leadership skills",
    ],
    responsibilities: [
      "Define product vision, strategy, and roadmap",
      "Gather and prioritize product requirements",
      "Work closely with engineering, design, and marketing teams",
      "Analyze market trends and competitive landscape",
    ],
  },
  {
    id: 12,
    title: "QA Engineer",
    company: "QualityTech",
    location: "Chennai, India",
    salary: "₹8,00,000 - ₹14,00,000",
    postedAt: "3 days ago",
    tags: ["Remote", "Full-Time", "Testing", "Automation", "Selenium"],
    employmentType: "Full-Time",
    description:
      "Join our QA team to ensure the quality of our software products through manual and automated testing processes.",
    requirements: [
      "3+ years of experience in software testing",
      "Knowledge of test automation frameworks like Selenium",
      "Experience with test planning and execution",
      "Understanding of Agile development methodologies",
    ],
    responsibilities: [
      "Design and execute test cases for web applications",
      "Develop and maintain automated test scripts",
      "Report and track bugs through issue tracking systems",
      "Collaborate with developers to resolve quality issues",
    ],
  },
  {
    id: 13,
    title: "Blockchain Developer",
    company: "BlockChainTech",
    location: "Gurgaon, India",
    salary: "₹18,00,000 - ₹28,00,000",
    postedAt: "4 days ago",
    tags: ["Hybrid", "Full-Time", "Blockchain", "Solidity", "Smart Contracts"],
    employmentType: "Full-Time",
    description:
      "We're seeking a Blockchain Developer to design and implement decentralized applications and smart contracts on various blockchain platforms.",
    requirements: [
      "3+ years of experience in blockchain development",
      "Proficiency in Solidity and smart contract development",
      "Understanding of blockchain consensus mechanisms",
      "Experience with web3.js or ethers.js",
    ],
    responsibilities: [
      "Design and develop smart contracts and dApps",
      "Implement security best practices for blockchain applications",
      "Integrate blockchain solutions with existing systems",
      "Stay updated with the latest blockchain technologies",
    ],
  },
  {
    id: 14,
    title: "Technical Writer",
    company: "DocuTech",
    location: "Noida, India",
    salary: "₹7,00,000 - ₹12,00,000",
    postedAt: "1 week ago",
    tags: ["Remote", "Full-Time", "Documentation", "Technical Writing"],
    employmentType: "Full-Time",
    description:
      "Join our team as a Technical Writer to create clear and concise documentation for our software products and APIs.",
    requirements: [
      "2+ years of experience in technical writing",
      "Strong understanding of software development concepts",
      "Excellent written and verbal communication skills",
      "Experience with documentation tools and platforms",
    ],
    responsibilities: [
      "Create and maintain technical documentation",
      "Work with engineers to understand product features",
      "Develop user guides, tutorials, and API documentation",
      "Ensure documentation is accurate and up-to-date",
    ],
  },
  {
    id: 15,
    title: "AI Research Scientist",
    company: "AIInnovate",
    location: "Bangalore, India",
    salary: "₹25,00,000 - ₹40,00,000",
    postedAt: "2 days ago",
    tags: ["On-site", "Full-Time", "AI", "Machine Learning", "Research"],
    employmentType: "Full-Time",
    description:
      "We are looking for an AI Research Scientist to advance our artificial intelligence capabilities and develop cutting-edge algorithms.",
    requirements: [
      "PhD in Computer Science, AI, or related field",
      "Strong publication record in AI or machine learning",
      "Experience with deep learning frameworks",
      "Excellent problem-solving and analytical skills",
    ],
    responsibilities: [
      "Conduct research in artificial intelligence and machine learning",
      "Develop and implement novel algorithms",
      "Publish research findings in academic journals and conferences",
      "Collaborate with engineering teams to implement research into products",
    ],
  },
  {
    id: 16,
    title: "Cloud Architect",
    company: "CloudSolutions",
    location: "Mumbai, India",
    salary: "₹22,00,000 - ₹35,00,000",
    postedAt: "5 days ago",
    tags: ["Hybrid", "Full-Time", "AWS", "Azure", "Cloud Architecture"],
    employmentType: "Full-Time",
    description:
      "Join our team as a Cloud Architect to design and implement scalable, secure, and resilient cloud infrastructure solutions.",
    requirements: [
      "5+ years of experience in cloud architecture",
      "Certifications in AWS, Azure, or GCP",
      "Experience with infrastructure as code tools",
      "Strong understanding of security best practices",
    ],
    responsibilities: [
      "Design and implement cloud architecture solutions",
      "Develop migration strategies for on-premise to cloud",
      "Ensure security, compliance, and cost optimization",
      "Mentor and guide development teams on cloud best practices",
    ],
  },
  {
    id: 17,
    title: "Game Developer",
    company: "GameStudio",
    location: "Pune, India",
    salary: "₹10,00,000 - ₹18,00,000",
    postedAt: "3 days ago",
    tags: ["On-site", "Full-Time", "Unity", "C#", "Game Development"],
    employmentType: "Full-Time",
    description:
      "We're looking for a talented Game Developer to join our creative team and build engaging gaming experiences across multiple platforms.",
    requirements: [
      "3+ years of experience in game development",
      "Proficiency with Unity or Unreal Engine",
      "Strong programming skills in C# or C++",
      "Understanding of game physics and mechanics",
    ],
    responsibilities: [
      "Develop game features and mechanics",
      "Optimize game performance across platforms",
      "Collaborate with artists and designers",
      "Fix bugs and implement improvements based on feedback",
    ],
  },
  {
    id: 18,
    title: "Cybersecurity Analyst",
    company: "SecureTech",
    location: "Hyderabad, India",
    salary: "₹12,00,000 - ₹20,00,000",
    postedAt: "1 week ago",
    tags: ["On-site", "Full-Time", "Security", "Penetration Testing"],
    employmentType: "Full-Time",
    description:
      "Join our security team to protect our systems and data from cyber threats through monitoring, analysis, and implementation of security measures.",
    requirements: [
      "3+ years of experience in cybersecurity",
      "Knowledge of security frameworks and compliance standards",
      "Experience with security tools and penetration testing",
      "Security certifications (CISSP, CEH, or equivalent)",
    ],
    responsibilities: [
      "Monitor systems for security breaches and incidents",
      "Conduct vulnerability assessments and penetration testing",
      "Implement security measures and best practices",
      "Respond to and investigate security incidents",
    ],
  },
  {
    id: 19,
    title: "Data Engineer",
    company: "DataFlow",
    location: "Chennai, India",
    salary: "₹14,00,000 - ₹22,00,000",
    postedAt: "4 days ago",
    tags: ["Remote", "Full-Time", "Python", "SQL", "ETL"],
    employmentType: "Full-Time",
    description:
      "We are seeking a Data Engineer to build and maintain our data infrastructure, ensuring efficient data processing and availability for analysis.",
    requirements: [
      "4+ years of experience in data engineering",
      "Strong SQL and Python programming skills",
      "Experience with ETL processes and data warehousing",
      "Knowledge of big data technologies (Hadoop, Spark)",
    ],
    responsibilities: [
      "Design and implement data pipelines and ETL processes",
      "Maintain and optimize database systems",
      "Ensure data quality, security, and availability",
      "Collaborate with data scientists and analysts",
    ],
  },
  {
    id: 20,
    title: "AR/VR Developer",
    company: "ImmersiveTech",
    location: "Bangalore, India",
    salary: "₹15,00,000 - ₹25,00,000",
    postedAt: "2 days ago",
    tags: ["On-site", "Full-Time", "Unity", "AR", "VR"],
    employmentType: "Full-Time",
    description:
      "Join our innovative team to develop augmented and virtual reality applications that push the boundaries of immersive experiences.",
    requirements: [
      "3+ years of experience in AR/VR development",
      "Proficiency with Unity or Unreal Engine",
      "Experience with AR/VR SDKs (ARKit, ARCore, Vuforia)",
      "Strong 3D mathematics and computer graphics knowledge",
    ],
    responsibilities: [
      "Develop AR/VR applications for various platforms",
      "Implement interactive 3D experiences",
      "Optimize performance for mobile and headset devices",
      "Collaborate with 3D artists and UX designers",
    ],
  },
  {
    id: 21,
    title: "Technical Project Manager",
    company: "ProjectPro",
    location: "Gurgaon, India",
    salary: "₹18,00,000 - ₹28,00,000",
    postedAt: "5 days ago",
    tags: ["Hybrid", "Full-Time", "Project Management", "Agile", "Scrum"],
    employmentType: "Full-Time",
    description:
      "We're looking for a Technical Project Manager to lead software development projects from inception to delivery, ensuring timely and quality results.",
    requirements: [
      "5+ years of experience in technical project management",
      "PMP or Agile certifications",
      "Strong understanding of software development lifecycle",
      "Excellent leadership and communication skills",
    ],
    responsibilities: [
      "Plan and execute software development projects",
      "Manage project scope, schedule, and resources",
      "Lead cross-functional teams and remove obstacles",
      "Report project status to stakeholders",
    ],
  },
  {
    id: 22,
    title: "Database Administrator",
    company: "DataGuard",
    location: "Mumbai, India",
    salary: "₹12,00,000 - ₹20,00,000",
    postedAt: "3 days ago",
    tags: ["On-site", "Full-Time", "SQL", "Oracle", "Database Management"],
    employmentType: "Full-Time",
    description:
      "Join our team as a Database Administrator to ensure the performance, security, and availability of our database systems.",
    requirements: [
      "4+ years of experience as a DBA",
      "Expertise in Oracle, SQL Server, or PostgreSQL",
      "Knowledge of database security and backup strategies",
      "Experience with performance tuning and optimization",
    ],
    responsibilities: [
      "Install, configure, and maintain database systems",
      "Implement backup and recovery procedures",
      "Monitor database performance and optimize queries",
      "Ensure data security and integrity",
    ],
  },
  {
    id: 23,
    title: "IoT Developer",
    company: "ConnectedTech",
    location: "Pune, India",
    salary: "₹14,00,000 - ₹22,00,000",
    postedAt: "1 week ago",
    tags: ["Hybrid", "Full-Time", "IoT", "Embedded Systems", "C++"],
    employmentType: "Full-Time",
    description:
      "We are seeking an IoT Developer to design and implement connected device solutions that bridge the physical and digital worlds.",
    requirements: [
      "3+ years of experience in IoT development",
      "Knowledge of embedded systems and microcontrollers",
      "Experience with IoT protocols (MQTT, CoAP)",
      "Programming skills in C/C++ or Python",
    ],
    responsibilities: [
      "Develop firmware for IoT devices",
      "Implement communication between devices and cloud",
      "Ensure security of IoT systems",
      "Collaborate with hardware engineers and backend developers",
    ],
  },
  {
    id: 24,
    title: "Machine Learning Engineer",
    company: "AITech",
    location: "Hyderabad, India",
    salary: "₹16,00,000 - ₹26,00,000",
    postedAt: "4 days ago",
    tags: ["Remote", "Full-Time", "Python", "TensorFlow", "Machine Learning"],
    employmentType: "Full-Time",
    description:
      "Join our AI team to build and deploy machine learning models that solve real-world problems and enhance our product capabilities.",
    requirements: [
      "3+ years of experience in machine learning engineering",
      "Strong programming skills in Python",
      "Experience with ML frameworks like TensorFlow or PyTorch",
      "Knowledge of model deployment and MLOps",
    ],
    responsibilities: [
      "Develop and implement machine learning models",
      "Deploy models to production environments",
      "Optimize model performance and accuracy",
      "Collaborate with data scientists and product teams",
    ],
  },
  {
    id: 25,
    title: "Site Reliability Engineer",
    company: "ReliableTech",
    location: "Bangalore, India",
    salary: "₹18,00,000 - ₹28,00,000",
    postedAt: "2 days ago",
    tags: ["On-site", "Full-Time", "DevOps", "Kubernetes", "Monitoring"],
    employmentType: "Full-Time",
    description:
      "We're looking for a Site Reliability Engineer to ensure the reliability, performance, and scalability of our production systems.",
    requirements: [
      "4+ years of experience in SRE or DevOps roles",
      "Strong knowledge of Linux/Unix systems",
      "Experience with containerization and orchestration",
      "Familiarity with monitoring and alerting systems",
    ],
    responsibilities: [
      "Design and implement infrastructure automation",
      "Monitor system performance and reliability",
      "Implement incident response procedures",
      "Collaborate with development teams to improve system reliability",
    ],
  },
  {
    id: 26,
    title: "Embedded Systems Engineer",
    company: "EmbedTech",
    location: "Chennai, India",
    salary: "₹12,00,000 - ₹20,00,000",
    postedAt: "5 days ago",
    tags: ["On-site", "Full-Time", "Embedded", "C/C++", "Firmware"],
    employmentType: "Full-Time",
    description:
      "Join our hardware team to develop firmware and software for embedded systems that power our innovative products.",
    requirements: [
      "3+ years of experience in embedded systems development",
      "Strong programming skills in C/C++",
      "Experience with microcontrollers and real-time operating systems",
      "Knowledge of hardware interfaces and protocols",
    ],
    responsibilities: [
      "Develop firmware for embedded devices",
      "Design and implement hardware interfaces",
      "Optimize code for performance and memory constraints",
      "Collaborate with hardware engineers for system integration",
    ],
  },
  {
    id: 27,
    title: "Salesforce Developer",
    company: "CloudForce",
    location: "Gurgaon, India",
    salary: "₹10,00,000 - ₹18,00,000",
    postedAt: "3 days ago",
    tags: ["Remote", "Full-Time", "Salesforce", "Apex", "Lightning"],
    employmentType: "Full-Time",
    description:
      "We are seeking a Salesforce Developer to design, build, and implement custom solutions on the Salesforce platform for our clients.",
    requirements: [
      "3+ years of experience in Salesforce development",
      "Salesforce certifications (Platform Developer, App Builder)",
      "Proficiency in Apex, Lightning, and Visualforce",
      "Experience with Salesforce integrations",
    ],
    responsibilities: [
      "Develop custom applications on Salesforce platform",
      "Implement business logic using Apex and Lightning",
      "Integrate Salesforce with external systems",
      "Provide technical solutions to meet business requirements",
    ],
  },
  {
    id: 28,
    title: "UI/UX Researcher",
    company: "UserFirst",
    location: "Mumbai, India",
    salary: "₹8,00,000 - ₹15,00,000",
    postedAt: "1 week ago",
    tags: ["Hybrid", "Full-Time", "User Research", "Usability Testing"],
    employmentType: "Full-Time",
    description:
      "Join our design team as a UI/UX Researcher to understand user needs and behaviors, informing the design of intuitive and effective user experiences.",
    requirements: [
      "2+ years of experience in user research",
      "Background in psychology, HCI, or related field",
      "Experience with various research methodologies",
      "Strong analytical and communication skills",
    ],
    responsibilities: [
      "Plan and conduct user research studies",
      "Analyze research data and identify insights",
      "Create personas, journey maps, and other UX artifacts",
      "Present findings to design and product teams",
    ],
  },
  {
    id: 29,
    title: "Network Engineer",
    company: "NetConnect",
    location: "Pune, India",
    salary: "₹10,00,000 - ₹16,00,000",
    postedAt: "4 days ago",
    tags: ["On-site", "Full-Time", "Networking", "Cisco", "Security"],
    employmentType: "Full-Time",
    description:
      "We're looking for a Network Engineer to design, implement, and maintain our network infrastructure, ensuring reliability and security.",
    requirements: [
      "3+ years of experience in network engineering",
      "CCNA/CCNP or equivalent certifications",
      "Experience with network equipment (Cisco, Juniper)",
      "Knowledge of network security principles",
    ],
    responsibilities: [
      "Design and implement network solutions",
      "Configure and maintain network equipment",
      "Troubleshoot network issues and outages",
      "Implement network security measures",
    ],
  },
  {
    id: 30,
    title: "Technical Support Engineer",
    company: "SupportTech",
    location: "Bangalore, India",
    salary: "₹6,00,000 - ₹10,00,000",
    postedAt: "2 days ago",
    tags: ["Remote", "Full-Time", "Technical Support", "Troubleshooting"],
    employmentType: "Full-Time",
    description:
      "Join our support team to provide technical assistance to customers, troubleshoot issues, and ensure a positive user experience with our products.",
    requirements: [
      "2+ years of experience in technical support",
      "Strong problem-solving and troubleshooting skills",
      "Excellent communication and customer service abilities",
      "Knowledge of IT systems and software applications",
    ],
    responsibilities: [
      "Respond to customer inquiries and technical issues",
      "Troubleshoot and resolve software and hardware problems",
      "Document solutions and maintain knowledge base",
      "Escalate complex issues to appropriate teams",
    ],
  },
  {
    id: 31,
    title: "React Native Developer",
    company: "MobileApps",
    location: "Hyderabad, India",
    salary: "₹12,00,000 - ₹18,00,000",
    postedAt: "5 days ago",
    tags: ["Hybrid", "Full-Time", "React Native", "JavaScript", "Mobile"],
    employmentType: "Full-Time",
    description:
      "We are seeking a React Native Developer to build cross-platform mobile applications with native-like performance and user experience.",
    requirements: [
      "3+ years of experience with React Native",
      "Strong JavaScript/TypeScript skills",
      "Experience with state management (Redux, Context API)",
      "Understanding of native mobile development concepts",
    ],
    responsibilities: [
      "Develop mobile applications using React Native",
      "Implement responsive UI components",
      "Integrate with backend APIs and services",
      "Optimize app performance and user experience",
    ],
  },
  {
    id: 32,
    title: "Python Developer",
    company: "PythonTech",
    location: "Delhi, India",
    salary: "₹10,00,000 - ₹16,00,000",
    postedAt: "3 days ago",
    tags: ["Remote", "Full-Time", "Python", "Django", "Flask"],
    employmentType: "Full-Time",
    description:
      "Join our development team to build and maintain Python-based applications and services that power our business operations.",
    requirements: [
      "3+ years of experience in Python development",
      "Proficiency with web frameworks like Django or Flask",
      "Experience with database design and ORM",
      "Knowledge of RESTful API development",
    ],
    responsibilities: [
      "Develop and maintain Python applications",
      "Design and implement database schemas",
      "Create and document APIs for frontend consumption",
      "Write clean, testable, and efficient code",
    ],
  },
  {
    id: 33,
    title: "Java Developer",
    company: "JavaSoft",
    location: "Kolkata, India",
    salary: "₹8,00,000 - ₹15,00,000",
    postedAt: "1 week ago",
    tags: ["On-site", "Full-Time", "Java", "Spring Boot", "Microservices"],
    employmentType: "Full-Time",
    description:
      "We're looking for a Java Developer to design and build enterprise-grade applications using Java and related technologies.",
    requirements: [
      "3+ years of experience in Java development",
      "Knowledge of Spring Framework and Spring Boot",
      "Experience with microservices architecture",
      "Understanding of relational databases and SQL",
    ],
    responsibilities: [
      "Develop and maintain Java applications",
      "Design and implement RESTful services",
      "Write clean, efficient, and well-tested code",
      "Collaborate with frontend developers for integration",
    ],
  },
  {
    id: 34,
    title: "Information Security Analyst",
    company: "SecureData",
    location: "Chennai, India",
    salary: "₹12,00,000 - ₹20,00,000",
    postedAt: "4 days ago",
    tags: ["On-site", "Full-Time", "Security", "Compliance", "Risk Management"],
    employmentType: "Full-Time",
    description:
      "Join our security team to protect our information assets through risk assessment, security controls implementation, and compliance monitoring.",
    requirements: [
      "3+ years of experience in information security",
      "Knowledge of security frameworks (ISO 27001, NIST)",
      "Experience with security assessment tools",
      "Understanding of regulatory compliance requirements",
    ],
    responsibilities: [
      "Conduct security risk assessments",
      "Implement and maintain security controls",
      "Monitor compliance with security policies",
      "Respond to and investigate security incidents",
    ],
  },
  {
    id: 35,
    title: "Business Intelligence Analyst",
    company: "DataInsight",
    location: "Pune, India",
    salary: "₹10,00,000 - ₹16,00,000",
    postedAt: "2 days ago",
    tags: ["Hybrid", "Full-Time", "SQL", "Tableau", "Data Analysis"],
    employmentType: "Full-Time",
    description:
      "We are seeking a Business Intelligence Analyst to transform data into actionable insights that drive business decisions and strategy.",
    requirements: [
      "3+ years of experience in business intelligence or data analysis",
      "Strong SQL skills and database knowledge",
      "Proficiency with BI tools like Tableau or Power BI",
      "Experience with data modeling and ETL processes",
    ],
    responsibilities: [
      "Design and build dashboards and reports",
      "Analyze data to identify trends and insights",
      "Collaborate with stakeholders to understand business needs",
      "Present findings and recommendations to management",
    ],
  },
  {
    id: 36,
    title: "WordPress Developer",
    company: "WebPress",
    location: "Mumbai, India",
    salary: "₹6,00,000 - ₹12,00,000",
    postedAt: "5 days ago",
    tags: ["Remote", "Full-Time", "WordPress", "PHP", "JavaScript"],
    employmentType: "Full-Time",
    description:
      "Join our web development team to create custom WordPress themes and plugins that deliver exceptional user experiences for our clients.",
    requirements: [
      "2+ years of experience in WordPress development",
      "Strong knowledge of PHP, HTML, CSS, and JavaScript",
      "Experience with theme and plugin development",
      "Understanding of WordPress best practices",
    ],
    responsibilities: [
      "Develop custom WordPress themes and plugins",
      "Customize existing themes to meet client requirements",
      "Ensure website performance and security",
      "Provide technical support for WordPress sites",
    ],
  },
]

